// <auto-generated />
namespace LearnIT.Infraestructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FileNameAdded2Photo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FileNameAdded2Photo));
        
        string IMigrationMetadata.Id
        {
            get { return "201607022352171_FileNameAdded2Photo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
